---
# TODO: Make this configuration work with nginx, apache, all OSes.
- name: Add Apache virtualhost for Drupal.
  template:
    src: drupal-vhost.conf.j2
    dest: "/{{ drupal_sites_conf_path }}/{{ drupal_domain }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart webserver
